
// Generated 2014-02-01 15:20:17 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import java.util.Vector;

/**
 * Adres generated by hbm2java
 */
public class Adres  implements java.io.Serializable {


     private long idAdresu;
     private KodPocztowy kodPocztowy;
     private String ulica;
     private short nrDomu;
     private Short nrLokalu;
     /////////////////////////
     private Set zleceniesForIdMety = new HashSet(0);
     private Set oddzials = new HashSet(0);
     private Set pracowniks = new HashSet(0);
     private Set zleceniesForIdStartu = new HashSet(0);
     private Set kontrahents = new HashSet(0);

    public Adres() {
    }

	
    public Adres(long idAdresu, KodPocztowy kodPocztowy, String ulica, short nrDomu) {
        this.idAdresu = idAdresu;
        this.kodPocztowy = kodPocztowy;
        this.ulica = ulica;
        this.nrDomu = nrDomu;
    }
    public Adres(long idAdresu, KodPocztowy kodPocztowy, String ulica, short nrDomu, Short nrLokalu, Set zleceniesForIdMety, Set oddzials, Set pracowniks, Set zleceniesForIdStartu, Set kontrahents) {
       this.idAdresu = idAdresu;
       this.kodPocztowy = kodPocztowy;
       this.ulica = ulica;
       this.nrDomu = nrDomu;
       this.nrLokalu = nrLokalu;
       this.zleceniesForIdMety = zleceniesForIdMety;
       this.oddzials = oddzials;
       this.pracowniks = pracowniks;
       this.zleceniesForIdStartu = zleceniesForIdStartu;
       this.kontrahents = kontrahents;
    }
   
    public long getIdAdresu() {
        return this.idAdresu;
    }
    
    public void setIdAdresu(long idAdresu) {
        this.idAdresu = idAdresu;
    }
    public KodPocztowy getKodPocztowy() {
        return this.kodPocztowy;
    }
    
    public void setKodPocztowy(KodPocztowy kodPocztowy) {
        this.kodPocztowy = kodPocztowy;
    }
    public String getUlica() {
        return this.ulica;
    }
    
    public void setUlica(String ulica) {
        this.ulica = ulica;
    }
    public short getNrDomu() {
        return this.nrDomu;
    }
    
    public void setNrDomu(short nrDomu) {
        this.nrDomu = nrDomu;
    }
    public Short getNrLokalu() {
        return this.nrLokalu;
    }
    
    public void setNrLokalu(Short nrLokalu) {
        this.nrLokalu = nrLokalu;
    }
    public Set getZleceniesForIdMety() {
        return this.zleceniesForIdMety;
    }
    
    public void setZleceniesForIdMety(Set zleceniesForIdMety) {
        this.zleceniesForIdMety = zleceniesForIdMety;
    }
    public Set getOddzials() {
        return this.oddzials;
    }
    
    public void setOddzials(Set oddzials) {
        this.oddzials = oddzials;
    }
    public Set getPracowniks() {
        return this.pracowniks;
    }
    
    public void setPracowniks(Set pracowniks) {
        this.pracowniks = pracowniks;
    }
    public Set getZleceniesForIdStartu() {
        return this.zleceniesForIdStartu;
    }
    
    public void setZleceniesForIdStartu(Set zleceniesForIdStartu) {
        this.zleceniesForIdStartu = zleceniesForIdStartu;
    }
    public Set getKontrahents() {
        return this.kontrahents;
    }
    
    public void setKontrahents(Set kontrahents) {
        this.kontrahents = kontrahents;
    }
    public static Class getKlasa(int kolumna)
    {
        if(kolumna ==0)
        {
            return long.class;
        }
        else if(kolumna ==1)
        {
            return KodPocztowy.class;
        }
        else if(kolumna ==2)
        {
            return String.class;
        }
        else if(kolumna ==3)
        {
            return Short.class;
        }
        else if(kolumna ==3)
        {
            return Short.class;
        }
         return Object.class;
        
    }
    public static Vector getKolumny()
    {
        Vector<String> result = new Vector<>();
        result.add("ID");
        result.add("Kod pocztowy");
        result.add("Ulica");
        result.add("Numer domu");
        result.add("Numer lokalu");
        //result.add("Adres");
        //String[] newt = new String[]{"ID", "Kod pocztowy", "Miasto", "Adres"};
        return  result;
    }

    public String toString()
    {
        return kodPocztowy + "" + ulica + " " + nrDomu + " " + nrLokalu;
    }

}


