
// Generated 2014-02-01 15:20:17 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import java.util.Vector;

/**
 * KodPocztowy generated by hbm2java
 */
public class KodPocztowy  implements java.io.Serializable {


     private long idKoduPoczt;
     private String kodPocztowy;
     private String miasto;
     private Set adreses = new HashSet(0);

    public KodPocztowy() {
    }

	
    public KodPocztowy(long idKoduPoczt, String kodPocztowy, String miasto) {
        this.idKoduPoczt = idKoduPoczt;
        this.kodPocztowy = kodPocztowy;
        this.miasto = miasto;
    }
    public KodPocztowy(long idKoduPoczt, String kodPocztowy, String miasto, Set adreses) {
       this.idKoduPoczt = idKoduPoczt;
       this.kodPocztowy = kodPocztowy;
       this.miasto = miasto;
       this.adreses = adreses;
    }
   
    public long getIdKoduPoczt() {
        return this.idKoduPoczt;
    }
    
    public void setIdKoduPoczt(long idKoduPoczt) {
        this.idKoduPoczt = idKoduPoczt;
    }
    public String getKodPocztowy() {
        return this.kodPocztowy;
    }
    
    public void setKodPocztowy(String kodPocztowy) {
        this.kodPocztowy = kodPocztowy;
    }
    public String getMiasto() {
        return this.miasto;
    }
    
    public void setMiasto(String miasto) {
        this.miasto = miasto;
    }
    public Set getAdreses() {
        return this.adreses;
    }
    
    public void setAdreses(Set adreses) {
        this.adreses = adreses;
    }

    public static Class getKlasa(int kolumna)
    {
        if(kolumna ==0)
        {
            return long.class;
        }
        else if(kolumna ==1)
        {
            return String.class;
        }
        else if(kolumna ==2)
        {
            return String.class;
        }
        /*else if(kolumna ==3)
        {
            return Set.class;
        }*/
         return Object.class;
        
    }
    public static Vector getKolumny()
    {
        Vector<String> result = new Vector<>();
        result.add("ID");
        result.add("Kod pocztowy");
        result.add("Miasto");
        //result.add("Adres");
        //String[] newt = new String[]{"ID", "Kod pocztowy", "Miasto", "Adres"};
        return  result;
    }
    public String toString()
    {
        return kodPocztowy + " " + miasto;
    }

}


