
// Generated 2014-02-01 15:20:17 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Ladunek generated by hbm2java
 */
public class Ladunek  implements java.io.Serializable {


     private long idLadunku;
     private TypTowaru typTowaru;
     private String nazwa;
     private long ilosc;
     private Set zlecenies = new HashSet(0);

    public Ladunek() {
    }

	
    public Ladunek(long idLadunku, TypTowaru typTowaru, String nazwa, long ilosc) {
        this.idLadunku = idLadunku;
        this.typTowaru = typTowaru;
        this.nazwa = nazwa;
        this.ilosc = ilosc;
    }
    public Ladunek(long idLadunku, TypTowaru typTowaru, String nazwa, long ilosc, Set zlecenies) {
       this.idLadunku = idLadunku;
       this.typTowaru = typTowaru;
       this.nazwa = nazwa;
       this.ilosc = ilosc;
       this.zlecenies = zlecenies;
    }
   
    public long getIdLadunku() {
        return this.idLadunku;
    }
    
    public void setIdLadunku(long idLadunku) {
        this.idLadunku = idLadunku;
    }
    public TypTowaru getTypTowaru() {
        return this.typTowaru;
    }
    
    public void setTypTowaru(TypTowaru typTowaru) {
        this.typTowaru = typTowaru;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    public long getIlosc() {
        return this.ilosc;
    }
    
    public void setIlosc(long ilosc) {
        this.ilosc = ilosc;
    }
    public Set getZlecenies() {
        return this.zlecenies;
    }
    
    public void setZlecenies(Set zlecenies) {
        this.zlecenies = zlecenies;
    }




}


