
import java.awt.Color;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.hibernate.*;
//import tabelki.KodPocztowy;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mehehe
 */
public class MajnOkienko extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MajnOkienko() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTP = new javax.swing.JTabbedPane();
        JTLogowanie = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        JTAdres = new javax.swing.JPanel();
        JTKodPocztowy = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTabKodPocztowyView = new javax.swing.JTable();
        jBKodPocztowyWyswietl = new javax.swing.JButton();
        jBKodPocztowyNewNowy = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTabKodPocztowyNew = new javax.swing.JTable();
        jBKodPocztowyNewWstaw = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTabKodPocztowyEdit = new javax.swing.JTable();
        jTFKodPocztowyEdit = new javax.swing.JTextField();
        jBKodPocztowyEditWczytaj = new javax.swing.JButton();
        jBKodPocztowyEditWstaw = new javax.swing.JButton();
        JTKontrahent = new javax.swing.JPanel();
        JTLadunek = new javax.swing.JPanel();
        JTModel = new javax.swing.JPanel();
        JTOddzial = new javax.swing.JPanel();
        JTPojazd = new javax.swing.JPanel();
        JTPracownik = new javax.swing.JPanel();
        JTSaldo = new javax.swing.JPanel();
        JTStatus = new javax.swing.JPanel();
        JTTypTowaru = new javax.swing.JPanel();
        JTWydatek = new javax.swing.JPanel();
        JTZlecenie = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jTFUsuwane = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 300));

        JTP.setBackground(new java.awt.Color(255, 153, 0));
        JTP.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        JTP.setDoubleBuffered(true);

        jPasswordField1.setText("Hasło");

        jTextField1.setText("Login");

        jLabel1.setText("Login");

        jLabel2.setText("Hasło");

        jButton1.setText("Zaloguj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JTLogowanieLayout = new javax.swing.GroupLayout(JTLogowanie);
        JTLogowanie.setLayout(JTLogowanieLayout);
        JTLogowanieLayout.setHorizontalGroup(
            JTLogowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JTLogowanieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JTLogowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addGroup(JTLogowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JTLogowanieLayout.createSequentialGroup()
                            .addGroup(JTLogowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(JTLogowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))))
                .addContainerGap(450, Short.MAX_VALUE))
        );
        JTLogowanieLayout.setVerticalGroup(
            JTLogowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JTLogowanieLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(JTLogowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JTLogowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(440, Short.MAX_VALUE))
        );

        JTP.addTab("LOGOWANIE", JTLogowanie);

        javax.swing.GroupLayout JTAdresLayout = new javax.swing.GroupLayout(JTAdres);
        JTAdres.setLayout(JTAdresLayout);
        JTAdresLayout.setHorizontalGroup(
            JTAdresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        JTAdresLayout.setVerticalGroup(
            JTAdresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        JTP.addTab("ADRES", JTAdres);

        JTabKodPocztowyView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTabKodPocztowyView);

        jBKodPocztowyWyswietl.setText("Wyświetl");
        jBKodPocztowyWyswietl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBKodPocztowyWyswietlActionPerformed(evt);
            }
        });

        jBKodPocztowyNewNowy.setText("Nowy");
        jBKodPocztowyNewNowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBKodPocztowyNewNowyActionPerformed(evt);
            }
        });

        JTabKodPocztowyNew.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(JTabKodPocztowyNew);

        jBKodPocztowyNewWstaw.setText("Wstaw");
        jBKodPocztowyNewWstaw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBKodPocztowyNewWstawActionPerformed(evt);
            }
        });

        JTabKodPocztowyEdit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(JTabKodPocztowyEdit);

        jTFKodPocztowyEdit.setText("ID edytowanego");
        jTFKodPocztowyEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFKodPocztowyEditActionPerformed(evt);
            }
        });

        jBKodPocztowyEditWczytaj.setText("Wczytaj");
        jBKodPocztowyEditWczytaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBKodPocztowyEditWczytajActionPerformed(evt);
            }
        });

        jBKodPocztowyEditWstaw.setText("Wstaw");
        jBKodPocztowyEditWstaw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBKodPocztowyEditWstawActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JTKodPocztowyLayout = new javax.swing.GroupLayout(JTKodPocztowy);
        JTKodPocztowy.setLayout(JTKodPocztowyLayout);
        JTKodPocztowyLayout.setHorizontalGroup(
            JTKodPocztowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane3)
            .addGroup(JTKodPocztowyLayout.createSequentialGroup()
                .addGroup(JTKodPocztowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBKodPocztowyWyswietl)
                    .addGroup(JTKodPocztowyLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jBKodPocztowyNewNowy)
                        .addGap(18, 18, 18)
                        .addComponent(jBKodPocztowyNewWstaw))
                    .addGroup(JTKodPocztowyLayout.createSequentialGroup()
                        .addComponent(jTFKodPocztowyEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBKodPocztowyEditWczytaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBKodPocztowyEditWstaw))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        JTKodPocztowyLayout.setVerticalGroup(
            JTKodPocztowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JTKodPocztowyLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBKodPocztowyWyswietl)
                .addGap(67, 67, 67)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JTKodPocztowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBKodPocztowyNewNowy)
                    .addComponent(jBKodPocztowyNewWstaw))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JTKodPocztowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFKodPocztowyEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBKodPocztowyEditWczytaj)
                    .addComponent(jBKodPocztowyEditWstaw))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        JTP.addTab("KOD POCZTOWY", JTKodPocztowy);

        javax.swing.GroupLayout JTKontrahentLayout = new javax.swing.GroupLayout(JTKontrahent);
        JTKontrahent.setLayout(JTKontrahentLayout);
        JTKontrahentLayout.setHorizontalGroup(
            JTKontrahentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        JTKontrahentLayout.setVerticalGroup(
            JTKontrahentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        JTP.addTab("KONTRAHENT", JTKontrahent);

        javax.swing.GroupLayout JTLadunekLayout = new javax.swing.GroupLayout(JTLadunek);
        JTLadunek.setLayout(JTLadunekLayout);
        JTLadunekLayout.setHorizontalGroup(
            JTLadunekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        JTLadunekLayout.setVerticalGroup(
            JTLadunekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        JTP.addTab("ŁADUNEK", JTLadunek);

        javax.swing.GroupLayout JTModelLayout = new javax.swing.GroupLayout(JTModel);
        JTModel.setLayout(JTModelLayout);
        JTModelLayout.setHorizontalGroup(
            JTModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        JTModelLayout.setVerticalGroup(
            JTModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        JTP.addTab("MODEL", JTModel);

        javax.swing.GroupLayout JTOddzialLayout = new javax.swing.GroupLayout(JTOddzial);
        JTOddzial.setLayout(JTOddzialLayout);
        JTOddzialLayout.setHorizontalGroup(
            JTOddzialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        JTOddzialLayout.setVerticalGroup(
            JTOddzialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        JTP.addTab("ODDZIAŁ", JTOddzial);

        javax.swing.GroupLayout JTPojazdLayout = new javax.swing.GroupLayout(JTPojazd);
        JTPojazd.setLayout(JTPojazdLayout);
        JTPojazdLayout.setHorizontalGroup(
            JTPojazdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        JTPojazdLayout.setVerticalGroup(
            JTPojazdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        JTP.addTab("POJAZD", JTPojazd);

        javax.swing.GroupLayout JTPracownikLayout = new javax.swing.GroupLayout(JTPracownik);
        JTPracownik.setLayout(JTPracownikLayout);
        JTPracownikLayout.setHorizontalGroup(
            JTPracownikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        JTPracownikLayout.setVerticalGroup(
            JTPracownikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        JTP.addTab("PRACOWNIK", JTPracownik);

        javax.swing.GroupLayout JTSaldoLayout = new javax.swing.GroupLayout(JTSaldo);
        JTSaldo.setLayout(JTSaldoLayout);
        JTSaldoLayout.setHorizontalGroup(
            JTSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        JTSaldoLayout.setVerticalGroup(
            JTSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        JTP.addTab("SALDO", JTSaldo);

        javax.swing.GroupLayout JTStatusLayout = new javax.swing.GroupLayout(JTStatus);
        JTStatus.setLayout(JTStatusLayout);
        JTStatusLayout.setHorizontalGroup(
            JTStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        JTStatusLayout.setVerticalGroup(
            JTStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        JTP.addTab("STATUS", JTStatus);

        javax.swing.GroupLayout JTTypTowaruLayout = new javax.swing.GroupLayout(JTTypTowaru);
        JTTypTowaru.setLayout(JTTypTowaruLayout);
        JTTypTowaruLayout.setHorizontalGroup(
            JTTypTowaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        JTTypTowaruLayout.setVerticalGroup(
            JTTypTowaruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        JTP.addTab("TYP TOWARU", JTTypTowaru);

        javax.swing.GroupLayout JTWydatekLayout = new javax.swing.GroupLayout(JTWydatek);
        JTWydatek.setLayout(JTWydatekLayout);
        JTWydatekLayout.setHorizontalGroup(
            JTWydatekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        JTWydatekLayout.setVerticalGroup(
            JTWydatekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        JTP.addTab("WYDATEK", JTWydatek);

        javax.swing.GroupLayout JTZlecenieLayout = new javax.swing.GroupLayout(JTZlecenie);
        JTZlecenie.setLayout(JTZlecenieLayout);
        JTZlecenieLayout.setHorizontalGroup(
            JTZlecenieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        JTZlecenieLayout.setVerticalGroup(
            JTZlecenieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        JTP.addTab("ZLECENIE", JTZlecenie);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ADRES\t", "KOD POCZTOWY", "KONTRAHENT", "ŁADUNEK", "MODEL", "ODDZIAŁ", "POJAZD", "PRACOWNIK", "SALDO", "STATUS", "TYP TOWARU", "WYDATEK", "ZLECENIE", " " }));

        jTFUsuwane.setText("ID usuwanego");

        jButton2.setText("Usuń");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTFUsuwane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(488, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFUsuwane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(535, Short.MAX_VALUE))
        );

        JTP.addTab("USUWANIE", jPanel1);

        JTP.setSelectedComponent(JTLogowanie);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(JTP, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(JTP, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String log, pass;
        log = jTextField1.getText();
        pass = new String(jPasswordField1.getPassword());
        Map<String, String> users= new HashMap<>();
        users.put("admin", "admin");
        users.put("flota", "flota");
        users.put("kadra", "kadra");
        users.put("szef", "szef");
        String res = users.get(log);
        if( res == null)
        {
            jLabel3.setText("Nie znaleziono użytkownika");
            jLabel3.setForeground(Color.red);
            JTP.setEnabled(false);
        }
        else
        {
            if(res.equals(pass))
            {
                jLabel3.setText("Zalogowano");
                jLabel3.setForeground(Color.green);
                JTP.setEnabled(true);
            }
            else
            {
                jLabel3.setText("Złe hasło");
                jLabel3.setForeground(Color.red);
                JTP.setEnabled(false);
            }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBKodPocztowyWyswietlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBKodPocztowyWyswietlActionPerformed
       String query = "from KodPocztowy";
       {
           try {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Query q = session.createQuery(query);
        List resultList = q.list();
        //displayResult(resultList);
        session.getTransaction().commit();
        Vector<String> tableHeaders = KodPocztowy.getKolumny();
        Vector tableData = new Vector();
        

    for(Object o : resultList) {
        KodPocztowy foteczka = (KodPocztowy)o;
        
        Vector<Object> oneRow = new Vector<Object>();
        oneRow.add(foteczka.getIdKoduPoczt());
        oneRow.add(foteczka.getKodPocztowy());
        oneRow.add(foteczka.getMiasto());
        //oneRow.add(foteczka.getAdreses());
        
        tableData.addElement(oneRow);
    }
    
    JTabKodPocztowyView.setModel(new DefaultTableModel(tableData, tableHeaders){
        public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }});
    } catch (HibernateException he) {
        he.printStackTrace();
    }
       }
        
    }//GEN-LAST:event_jBKodPocztowyWyswietlActionPerformed

    private void jBKodPocztowyNewNowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBKodPocztowyNewNowyActionPerformed
        KodPocztowy foteczka = new KodPocztowy(1, "09200", "Sierpc");
        Vector tableData = new Vector();
        Vector<Object> oneRow = new Vector<Object>();
        oneRow.add(foteczka.getIdKoduPoczt());
        oneRow.add(foteczka.getKodPocztowy());
        oneRow.add(foteczka.getMiasto());
        //oneRow.add(foteczka.getAdreses());
        tableData.addElement(oneRow);
        JTabKodPocztowyNew.setModel(new DefaultTableModel(tableData, KodPocztowy.getKolumny())
        {
            @Override
            public boolean isCellEditable(int row, int column) 
            {
                //if(column == 0)
                    //return false;
                return true;
            }
            @Override
            public Class getColumnClass(int col)
            {
                return KodPocztowy.getKlasa(col);
            }
        });
    }//GEN-LAST:event_jBKodPocztowyNewNowyActionPerformed

    private void jBKodPocztowyNewWstawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBKodPocztowyNewWstawActionPerformed
        long id = (long)JTabKodPocztowyNew.getValueAt(0, 0);
        String kod = (String)JTabKodPocztowyNew.getValueAt(0, 1);
        String miasto = (String)JTabKodPocztowyNew.getValueAt(0, 2);
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        
        session.save(new KodPocztowy(id,kod,miasto));
        session.getTransaction().commit();
        jBKodPocztowyWyswietlActionPerformed(null);
    }//GEN-LAST:event_jBKodPocztowyNewWstawActionPerformed

    private void jTFKodPocztowyEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFKodPocztowyEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFKodPocztowyEditActionPerformed

    private void jBKodPocztowyEditWczytajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBKodPocztowyEditWczytajActionPerformed
        long id = 0;
        try
        {
            id = Long.parseLong(jTFKodPocztowyEdit.getText());
        }
        catch(Exception e)
        {     
            JOptionPane.showMessageDialog(null, e.toString());
            
            //e.printStackTrace();
        }
        String query = "from KodPocztowy where idKoduPoczt="+id;
       {
           try {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Query q = session.createQuery(query);
        List resultList = q.list();
        //displayResult(resultList);
        session.getTransaction().commit();
        Vector<String> tableHeaders = KodPocztowy.getKolumny();
        Vector tableData = new Vector();
        

        for(Object o : resultList) {
        KodPocztowy foteczka = (KodPocztowy)o;
        
        Vector<Object> oneRow = new Vector<Object>();
        oneRow.add(foteczka.getIdKoduPoczt());
        oneRow.add(foteczka.getKodPocztowy());
        oneRow.add(foteczka.getMiasto());
        //oneRow.add(foteczka.getAdreses());
        
        tableData.addElement(oneRow);
    }
    
    JTabKodPocztowyEdit.setModel(new DefaultTableModel(tableData, tableHeaders){
        public boolean isCellEditable(int row, int column) {
       //all cells false
        if(column == 0)
            return false;
       return true;
    }});
    } catch (HibernateException he) {
        he.printStackTrace();
    }
       }
    }//GEN-LAST:event_jBKodPocztowyEditWczytajActionPerformed

    private void jBKodPocztowyEditWstawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBKodPocztowyEditWstawActionPerformed
        try
        {
            long id = (long)JTabKodPocztowyEdit.getValueAt(0, 0);
            String kod = (String)JTabKodPocztowyEdit.getValueAt(0, 1);
            String miasto = (String)JTabKodPocztowyEdit.getValueAt(0, 2);
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();

            session.update(new KodPocztowy(id,kod,miasto));
            session.getTransaction().commit();
        }
        catch(Exception e)
        {
            e.printStackTrace();
            return;
        }
        
        jBKodPocztowyWyswietlActionPerformed(null);
    }//GEN-LAST:event_jBKodPocztowyEditWstawActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int wybor = jComboBox1.getSelectedIndex();
        String idname = "";
        long idnr = 0;
        int ile = 0;
        try
        {
            idnr = Long.parseLong(jTFUsuwane.getText());
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Nie usunięto rekordu.\n"+e.toString());
            return;
        }
        try
        {
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();

            if(wybor==0)//adres
            {
                Query q = session.createQuery("delete Adres where idAdresu ="+idnr);
                ile = q.executeUpdate();
            }
            else if(wybor==1)//kod
            {
                Query q = session.createQuery("delete KodPocztowy where idKoduPoczt ="+idnr);
                ile = q.executeUpdate();
            }
            else if(wybor==2)//kontrahent
            {
                Query q = session.createQuery("delete Kontrahent where idKontrahenta ="+idnr);
                ile = q.executeUpdate();
            }
            else if(wybor==3)//ladunek
            {
                Query q = session.createQuery("delete Ladunek where idLadunku ="+idnr);
                ile = q.executeUpdate();
            }
            else if(wybor==4)//model
            {
                Query q = session.createQuery("delete Model where idModelu ="+idnr);
                ile = q.executeUpdate();
            }
            else if(wybor==5)//oddzial
            {
                Query q = session.createQuery("delete Oddzial where idInstytucji ="+idnr);
                ile = q.executeUpdate();
            }
            else if(wybor==6)//pojazd
            {
                Query q = session.createQuery("delete Pojazd where idPojazdu ="+idnr);
                ile = q.executeUpdate();
            }
            else if(wybor==7)//pracownik
            {
                Query q = session.createQuery("delete Pracownik where idPracownika ="+idnr);
                ile = q.executeUpdate();
            }
            else if(wybor==8)//saldo
            {
                Query q = session.createQuery("delete Saldo where idSalda ="+idnr);
                ile = q.executeUpdate();
            }
            else if(wybor==9)//status
            {
                Query q = session.createQuery("delete Status where stan ="+idnr);
                ile = q.executeUpdate();
            }
            else if(wybor==10)//typ
            {
                Query q = session.createQuery("delete TypTowaru where idTypu ="+idnr);
                ile = q.executeUpdate();
            }
            else if(wybor==11)//wydatek
            {
                Query q = session.createQuery("delete Wydatek where idWydatku ="+idnr);
                ile = q.executeUpdate();
            }
            else if(wybor==12)//zlecenie
            {
                Query q = session.createQuery("delete Zlecenie where idZlecenia ="+idnr);
                ile = q.executeUpdate();
            }
            session.getTransaction().commit();
    }
    catch(HibernateException e)
    {
        JOptionPane.showMessageDialog(null, "Jakiś błąd komunikacji z bazą,\nNa przykłąd nie ma obiektu o takim ID\n"+e.toString());
    }
        if(ile ==1)
            JOptionPane.showMessageDialog(null,"Usunięto pomyślnie");
        else
            JOptionPane.showMessageDialog(null,"Nic nie usunięto");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws java.lang.InstantiationException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MajnOkienko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MajnOkienko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MajnOkienko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MajnOkienko().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JTAdres;
    private javax.swing.JPanel JTKodPocztowy;
    private javax.swing.JPanel JTKontrahent;
    private javax.swing.JPanel JTLadunek;
    private javax.swing.JPanel JTLogowanie;
    private javax.swing.JPanel JTModel;
    private javax.swing.JPanel JTOddzial;
    private javax.swing.JTabbedPane JTP;
    private javax.swing.JPanel JTPojazd;
    private javax.swing.JPanel JTPracownik;
    private javax.swing.JPanel JTSaldo;
    private javax.swing.JPanel JTStatus;
    private javax.swing.JPanel JTTypTowaru;
    private javax.swing.JPanel JTWydatek;
    private javax.swing.JPanel JTZlecenie;
    private javax.swing.JTable JTabKodPocztowyEdit;
    private javax.swing.JTable JTabKodPocztowyNew;
    private javax.swing.JTable JTabKodPocztowyView;
    private javax.swing.JButton jBKodPocztowyEditWczytaj;
    private javax.swing.JButton jBKodPocztowyEditWstaw;
    private javax.swing.JButton jBKodPocztowyNewNowy;
    private javax.swing.JButton jBKodPocztowyNewWstaw;
    private javax.swing.JButton jBKodPocztowyWyswietl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTFKodPocztowyEdit;
    private javax.swing.JTextField jTFUsuwane;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
