
// Generated 2014-02-01 15:20:17 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import java.util.Vector;

/**
 * Model generated by hbm2java
 */
public class Model  implements java.io.Serializable {


     private long idModelu;
     private TypTowaru typTowaru;
     private String model;
     private String marka;
     private BigDecimal koszt;
     private BigDecimal predkosc;
     private long ladownosc;
     private Set pojazds = new HashSet(0);

    public Model() {
    }

	
    public Model(long idModelu, TypTowaru typTowaru, String model, String marka, BigDecimal koszt, BigDecimal predkosc, long ladownosc) {
        this.idModelu = idModelu;
        this.typTowaru = typTowaru;
        this.model = model;
        this.marka = marka;
        this.koszt = koszt;
        this.predkosc = predkosc;
        this.ladownosc = ladownosc;
    }
    public Model(long idModelu, TypTowaru typTowaru, String model, String marka, BigDecimal koszt, BigDecimal predkosc, long ladownosc, Set pojazds) {
       this.idModelu = idModelu;
       this.typTowaru = typTowaru;
       this.model = model;
       this.marka = marka;
       this.koszt = koszt;
       this.predkosc = predkosc;
       this.ladownosc = ladownosc;
       this.pojazds = pojazds;
    }
   
    public long getIdModelu() {
        return this.idModelu;
    }
    
    public void setIdModelu(long idModelu) {
        this.idModelu = idModelu;
    }
    public TypTowaru getTypTowaru() {
        return this.typTowaru;
    }
    
    public void setTypTowaru(TypTowaru typTowaru) {
        this.typTowaru = typTowaru;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public String getMarka() {
        return this.marka;
    }
    
    public void setMarka(String marka) {
        this.marka = marka;
    }
    public BigDecimal getKoszt() {
        return this.koszt;
    }
    
    public void setKoszt(BigDecimal koszt) {
        this.koszt = koszt;
    }
    public BigDecimal getPredkosc() {
        return this.predkosc;
    }
    
    public void setPredkosc(BigDecimal predkosc) {
        this.predkosc = predkosc;
    }
    public long getLadownosc() {
        return this.ladownosc;
    }
    
    public void setLadownosc(long ladownosc) {
        this.ladownosc = ladownosc;
    }
    public Set getPojazds() {
        return this.pojazds;
    }
    
    public void setPojazds(Set pojazds) {
        this.pojazds = pojazds;
    }

    public static Vector getKolumny()
    {
        Vector<String> result = new Vector<>();
        result.add("ID");
        result.add("Typ towaru");
        result.add("Model");
        result.add("Marka");
        result.add("Koszt miesięczny");
        result.add("Prędkość użytkowa");
        result.add("Ładowność");
        return  result;
        /* private long idModelu;
     private TypTowaru typTowaru;
     private String model;
     private String marka;
     private BigDecimal koszt;
     private BigDecimal predkosc;
     private long ladownosc;*/
    }

    public String toString()
    {
        return typTowaru + " " + model + " " + marka + " " + koszt + " " + predkosc + " " + ladownosc;
    }


}


