
// Generated 2014-02-01 15:20:17 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import java.util.Vector;

/**
 * Oddzial generated by hbm2java
 */
public class Oddzial  implements java.io.Serializable {


     private long idInstytucji;
     private Adres adres;
     private String nazwaInstytucji;
     private Set saldos = new HashSet(0);
     private Set pracowniks = new HashSet(0);
     private Set wydateks = new HashSet(0);

    public Oddzial() {
    }

	
    public Oddzial(long idInstytucji, Adres adres, String nazwaInstytucji) {
        this.idInstytucji = idInstytucji;
        this.adres = adres;
        this.nazwaInstytucji = nazwaInstytucji;
    }
    public Oddzial(long idInstytucji, Adres adres, String nazwaInstytucji, Set saldos, Set pracowniks, Set wydateks) {
       this.idInstytucji = idInstytucji;
       this.adres = adres;
       this.nazwaInstytucji = nazwaInstytucji;
       this.saldos = saldos;
       this.pracowniks = pracowniks;
       this.wydateks = wydateks;
    }
   
    public long getIdInstytucji() {
        return this.idInstytucji;
    }
    
    public void setIdInstytucji(long idInstytucji) {
        this.idInstytucji = idInstytucji;
    }
    public Adres getAdres() {
        return this.adres;
    }
    
    public void setAdres(Adres adres) {
        this.adres = adres;
    }
    public String getNazwaInstytucji() {
        return this.nazwaInstytucji;
    }
    
    public void setNazwaInstytucji(String nazwaInstytucji) {
        this.nazwaInstytucji = nazwaInstytucji;
    }
    public Set getSaldos() {
        return this.saldos;
    }
    
    public void setSaldos(Set saldos) {
        this.saldos = saldos;
    }
    public Set getPracowniks() {
        return this.pracowniks;
    }
    
    public void setPracowniks(Set pracowniks) {
        this.pracowniks = pracowniks;
    }
    public Set getWydateks() {
        return this.wydateks;
    }
    
    public void setWydateks(Set wydateks) {
        this.wydateks = wydateks;
    }

    public static Vector getKolumny()
    {
        Vector<String> result = new Vector<>();
        result.add("ID");
        result.add("Adres");
        result.add("Nazwa");
        
        return  result;
        /*private long idInstytucji;
     private Adres adres;
     private String nazwaInstytucji;*/
    }

    public String toString()
    {
        return adres + " " +nazwaInstytucji;
    }


}


