
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mehehe
 */
public class PojazdAddAndEdit extends javax.swing.JFrame {

    /**
     * Creates new form PojazdAddAndEdit
     */
    public PojazdAddAndEdit() {
        initComponents();
        Zacznij();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jCBWybór = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jCBWybierzModel = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jCBWybierPojazd = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pojazd - Dodaj lub Edytuj");
        setResizable(false);

        jCBWybór.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dodaj", "Edytuj" }));
        jCBWybór.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBWybórActionPerformed(evt);
            }
        });

        jLabel1.setText("Model");

        jCBWybierzModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBWybierzModelActionPerformed(evt);
            }
        });

        jLabel2.setText("Data przeglądu");

        jLabel3.setText("Data produkcji");

        jLabel4.setText("Numer Rejestracyjny");

        jCBWybierPojazd.setEnabled(false);
        jCBWybierPojazd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBWybierPojazdActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setText("Wstaw nowe/wyedytowane");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Wybierz czynność");

        jLabel6.setText("Wybierz edytowany pojazd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(82, 82, 82))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                            .addComponent(jCBWybór, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBWybierPojazd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jCBWybierzModel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBWybór, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBWybierPojazd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBWybierzModel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBWybórActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBWybórActionPerformed
                                                  
        if(jCBWybór.getSelectedIndex()==0)//dodaj
        {
            jCBWybierPojazd.setEnabled(false);
            jCBWybierPojazd.removeAllItems();
            jTextField1.setText("");
        }
        else if(jCBWybór.getSelectedIndex()==1)//edytuj
        {
            String query = "from Pojazd";
            {
                try 
                {
                    Session session = HibernateUtil.getSessionFactory().getCurrentSession();
                    session.beginTransaction();
                    Query q = session.createQuery(query);
                    List resultList = q.list();
                    //displayResult(resultList);
                    
                    //List<KodPocztowy> kody = new ArrayList<>();
                    //session.close();
                    jCBWybierPojazd.removeAllItems();
                    jCBWybierPojazd.setEnabled(true);
                    for(Object o : resultList) 
                    {
                        Pojazd adr = (Pojazd)o;
                        //kody.add(kod);
                        jCBWybierPojazd.addItem(adr);
                    }
                    
                    //session.getTransaction().commit();


                } 
                catch (HibernateException he) 
                {
                    he.printStackTrace();
                }
           }
        }     
    }//GEN-LAST:event_jCBWybórActionPerformed

    private void jCBWybierPojazdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBWybierPojazdActionPerformed
        
        Pojazd adr = (Pojazd)jCBWybierPojazd.getSelectedItem();
        if(adr==null)
            return;
        jTextField1.setText(adr.getNumerRejestracyjny());
        jDateChooser1.setDate(adr.getDataPrzegladu());
        jDateChooser2.setDate(adr.getDataProdukcji());
        Model kp = adr.getModel();
        for(int i=0; i<jCBWybierzModel.getItemCount();i++)
        {
            Model kp2= (Model)jCBWybierzModel.getItemAt(i);
            if(kp2.getIdModelu()==kp.getIdModelu())
                jCBWybierzModel.setSelectedIndex(i);
        }
    }//GEN-LAST:event_jCBWybierPojazdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Session session;
        try
        {
            Pojazd adr=new Pojazd();
            if(!Pojazd.verify(jTextField1.getText()))
                return;
            if(jCBWybór.getSelectedIndex()==1 && null!=jCBWybierPojazd.getSelectedItem())//jeśli edycja
            {
                adr = (Pojazd)jCBWybierPojazd.getSelectedItem();
                adr.setNumerRejestracyjny(jTextField1.getText());
                
                adr.setDataPrzegladu(jDateChooser1.getDate());
                adr.setDataProdukcji(jDateChooser2.getDate());
                adr.setModel((Model)jCBWybierzModel.getSelectedItem());
            }
            else if(jCBWybór.getSelectedIndex()==0)//dodawanie
            {
                
                adr.setNumerRejestracyjny(jTextField1.getText());
                
                adr.setDataPrzegladu(jDateChooser1.getDate());
                adr.setDataProdukcji(jDateChooser2.getDate());
                
                adr.setModel((Model)jCBWybierzModel.getSelectedItem());
            }
            
            session = HibernateUtil.getSessionFactory().getCurrentSession();
            session.beginTransaction();

            session.saveOrUpdate(adr);
            
            //session.close();

            
        }
        catch(HibernateException ex)
        {
            JOptionPane.showMessageDialog(null, "Jakiś błąd hibernate\n"+ex.toString());
            return;
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Jakiś błąd inny\n"+ex.toString());
            return;
        }
        JOptionPane.showMessageDialog(null,"Transakcja przebiegła pomyślnie");
        session.getTransaction().commit();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCBWybierzModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBWybierzModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBWybierzModelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PojazdAddAndEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PojazdAddAndEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PojazdAddAndEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PojazdAddAndEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PojazdAddAndEdit().setVisible(true);
            }
        });
    }
    
    public void Zacznij()
   {
        String query = "from Model";
        {
            try 
            {
                Session session = HibernateUtil.getSessionFactory().getCurrentSession();
                session.beginTransaction();
                Query q = session.createQuery(query);
                List resultList = q.list();
                //displayResult(resultList);
                
                //List<KodPocztowy> kody = new ArrayList<>();
                //session.close();
                jCBWybierzModel.removeAllItems();
                for(Object o : resultList) 
                {
                    Model kod = (Model)o;
                    jCBWybierzModel.addItem(kod);
                }
                //session.getTransaction().commit();
                

            } 
            catch (HibernateException he) 
            {
                he.printStackTrace();
            }
       }
        
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jCBWybierPojazd;
    private javax.swing.JComboBox jCBWybierzModel;
    private javax.swing.JComboBox jCBWybór;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
