
// Generated 2014-02-01 15:20:17 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.Vector;

/**
 * Saldo generated by hbm2java
 */
public class Saldo  implements java.io.Serializable {


     private long idSalda;
     private Oddzial oddzial;
     private BigDecimal kwota;
     private String informacje;
     private Date dataFaktury;

    public Saldo() {
    }

    public Saldo(long idSalda, Oddzial oddzial, BigDecimal kwota, String informacje, Date dataFaktury) {
       this.idSalda = idSalda;
       this.oddzial = oddzial;
       this.kwota = kwota;
       this.informacje = informacje;
       this.dataFaktury = dataFaktury;
    }
   
    public long getIdSalda() {
        return this.idSalda;
    }
    
    public void setIdSalda(long idSalda) {
        this.idSalda = idSalda;
    }
    public Oddzial getOddzial() {
        return this.oddzial;
    }
    
    public void setOddzial(Oddzial oddzial) {
        this.oddzial = oddzial;
    }
    public BigDecimal getKwota() {
        return this.kwota;
    }
    
    public void setKwota(BigDecimal kwota) {
        this.kwota = kwota;
    }
    public String getInformacje() {
        return this.informacje;
    }
    
    public void setInformacje(String informacje) {
        this.informacje = informacje;
    }
    public Date getDataFaktury() {
        return this.dataFaktury;
    }
    
    public void setDataFaktury(Date dataFaktury) {
        this.dataFaktury = dataFaktury;
    }

    public static Vector getKolumny()
    {
        Vector<String> result = new Vector<>();
        result.add("ID");
        result.add("Oddział");
        result.add("Kwota");
        result.add("Informacje");
        result.add("Data");
        
        return  result;
        /*private long idSalda;
     private Oddzial oddzial;
     private BigDecimal kwota;
     private String informacje;
     private Date dataFaktury;*/
    }

     @Override
    public String toString()
    {
        return oddzial + " " + kwota + " " + informacje + " " + dataFaktury;
    }


}


