
// Generated 2014-02-01 15:20:17 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import java.util.Vector;

/**
 * TypTowaru generated by hbm2java
 */
public class TypTowaru  implements java.io.Serializable {


     private long idTypu;
     private String typ;
     private Set models = new HashSet(0);
     private Set laduneks = new HashSet(0);

    public TypTowaru() {
    }

	
    public TypTowaru(long idTypu, String typ) {
        this.idTypu = idTypu;
        this.typ = typ;
    }
    public TypTowaru(long idTypu, String typ, Set models, Set laduneks) {
       this.idTypu = idTypu;
       this.typ = typ;
       this.models = models;
       this.laduneks = laduneks;
    }
   
    public long getIdTypu() {
        return this.idTypu;
    }
    
    public void setIdTypu(long idTypu) {
        this.idTypu = idTypu;
    }
    public String getTyp() {
        return this.typ;
    }
    
    public void setTyp(String typ) {
        this.typ = typ;
    }
    public Set getModels() {
        return this.models;
    }
    
    public void setModels(Set models) {
        this.models = models;
    }
    public Set getLaduneks() {
        return this.laduneks;
    }
    
    public void setLaduneks(Set laduneks) {
        this.laduneks = laduneks;
    }

    public static Vector getKolumny()
    {
        Vector<String> result = new Vector<>();
        result.add("ID");
        result.add("Typ");
        
        return  result;
        /* private long idTypu;
     private String typ;*/
    }

     @Override
    public String toString()
    {
        return typ;
    }


}


